language: scala
sudo: false
scala:
- 2.11.8
- 2.12.4
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_8387b4a44f2f_key -iv $encrypted_8387b4a44f2f_iv
  -in .credentials.enc -out .credentials -d
script: "./travis.sh"
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt  -name "*.lock"               -print -delete
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot"
  - "$HOME/.sbt"
